version: '3.8'
services:
  db:
    image: postgres:14.13-alpine3.20
    container_name: bi_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: bi_db
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"

  bi_python:
    build: .
    container_name: bi_python_container
    depends_on:
      - db
    volumes:
      - .:/app
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_NAME=bi_db
      - DB_USER=postgres
      - DB_PASS=postgres
    command: python app.py

volumes:
  pgdata:
